import { createElement } from 'react'
import { renderToBuffer } from '@react-pdf/renderer'
import * as fs from 'fs'
import * as path from 'path'
import { QuestionnairePdf, ServiceAgreementPdf, OnboardingPackagePdf } from '@fbsi/shared'
import type { FormValues } from '@fbsi/shared'

// Optional sample signature image (generated by PIL) → data URL, to preview the
// drawn/typed signature embedded in the Service Agreement. Falls back to /s/ Name.
function loadSampleSignature(): string {
  try {
    const p = path.join(process.cwd(), 'scripts', 'sample_signature.png')
    return `data:image/png;base64,${fs.readFileSync(p).toString('base64')}`
  } catch {
    return ''
  }
}

// Comprehensive test data matching a real 401(k) plan onboarding
const testValues: FormValues = {
  // Shared Core Basics
  companyName: 'Acme Enterprises Inc.',
  companyAddress: '456 Innovation Way, Tech City, CA 94016',
  entityType: 'C Corporation',
  controlledGroup: 'No',
  affiliatedServiceGroup: 'No',
  ein: '98-7654321',
  dateBusinessCommenced: '2015-03-15',
  taxYearEnd: '12/31',
  employerEmail: 'operations@acmeenterprises.com',
  employerPhone: '415-555-0199',
  planName: 'Acme Enterprises 401(k) Profit Sharing Plan',
  planTrustee: 'Robert E. Acme',
  planEffectiveDate: '2026-07-01',
  planYearEnd: '12/31',
  planNumber: '001',
  investmentProduct: 'Mutual Funds',
  anotherQualifiedPlan: 'No',

  // 401(k) Plan Design
  trustees: 'Individuals',
  eligibilityRequirements: '1 year',
  ageRequirements: '21',
  planEntryDates: 'Semi-Annually',
  recognizePriorEmployerService: 'No',
  vestingSchedule: '6 year graded',
  yearsForVesting: 'All Years',
  normalRetirementAge: '65',
  modifyDeferralFrequency: 'Payroll Period',
  oneTimeDeferralOnBonus: 'Yes',
  allowRoth: 'Yes',
  commenceDeferralsAfterEligible: 'Immediately',
  autoEnrollment: 'Yes',
  autoEnrollmentPercent: '3%',
  employerMatch: 'Yes',
  matchingFormula: '100% on first 3%, plus 50% on next 2%',
  matchingFrequency: 'Per Payroll Period',
  matchingHours: 'None (typical)',
  matchingForfeitureThen: 'Used to Reduce future contributions (typical)',
  profitSharingOffered: 'Yes',
  profitSharingFormula: 'Discretionary Pro-Rata',
  loans: 'Yes',
  loanLimitations: 'Minimum loan of $1,000.00 (typical)',
  refinanceLoans: 'No',
  transfersFromOtherPlan: 'No',
  hardshipDistributions: 'From Employee Deferrals Only (typical)',
  inServiceDistributions: 'Yes',
  distributionFeesPaidByParticipants: 'Yes',
  forceOutThreshold: 'Less than $1,000 (paid to participant)',
  safeHarbor: 'No',
  adpAcpTestingMethod: 'Current Year',

  // Operational Sections
  newOrExistingPlan: 'New',
  primaryContactName: 'Robert E. Acme',
  primaryContactEmail: 'robert@acmeenterprises.com',
  primaryContactPhone: '415-555-0100',
  primaryIsAuthorizedSigner: 'Yes',

  separateDivisions: 'No',
  payrollFrequency: 'Semi-Monthly',
  payrollWhenPaid: '15th and Last day of month',

  advisorFirmName: 'Apex Wealth Advisors',
  advisorFeeArrangement: 'Option 1 — Asset-Based Fee (percentage of assets)',
  advisorFeePercent: '0.50%',

  defaultFundType: 'Target Date Funds',
  fundLineup: JSON.stringify([
    { ticker: 'VFIAX', fundName: 'Vanguard 500 Index Fund', cusip: '922908710', etf: 'No', notes: 'Core Equity' },
    { ticker: 'VBTLX', fundName: 'Vanguard Total Bond Market Index', cusip: '922908769', etf: 'No', notes: 'Core Fixed Income' },
    { ticker: 'VTINX', fundName: 'Vanguard Target Retirement Income', cusip: '922908207', etf: 'No', notes: 'Default Target Date' }
  ]),

  // E-SIGN/UETA consent + electronic signature (authorized-signer path)
  esignConsent: 'Yes',
  esignConsentAt: '2026-06-17T14:30:00.000Z',
  slaSignerAuthorized: 'Yes',
  slaSignerName: 'Robert E. Acme',
  slaSignerTitle: 'President & Trustee',
  slaSignatureImage: loadSampleSignature(),
  slaAcknowledged: 'Yes',
  slaSignedAt: '2026-06-17T14:32:00.000Z',

  // Final data certification
  dataCertified: 'Yes',
  dataCertifiedBy: 'Robert E. Acme',
  dataCertifiedAt: '2026-06-17T14:40:00.000Z',
}

async function main() {
  const planType = '401k'
  console.log(`Generating draft PDFs for: ${planType}...`)

  // 1. Generate Questionnaire Onboarding Summary
  const qElement = createElement(QuestionnairePdf, { planType, values: testValues })
  const qBuffer = await renderToBuffer(qElement)
  const qPath = path.join(process.cwd(), 'Acme_Enterprises-401k-Draft-OnboardingSummary.pdf')
  fs.writeFileSync(qPath, qBuffer)
  console.log(`Generated: ${qPath} (${qBuffer.length} bytes)`)

  // 2. Generate Service Agreement
  const slaElement = createElement(ServiceAgreementPdf, { planType, values: testValues })
  const slaBuffer = await renderToBuffer(slaElement)
  const slaPath = path.join(process.cwd(), 'Acme_Enterprises-401k-Draft-ServiceAgreement.pdf')
  fs.writeFileSync(slaPath, slaBuffer)
  console.log(`Generated: ${slaPath} (${slaBuffer.length} bytes)`)

  // 3. Generate the combined Onboarding Package (cover + SA + summary)
  const pkgElement = createElement(OnboardingPackagePdf, { planType, values: testValues })
  const pkgBuffer = await renderToBuffer(pkgElement)
  const pkgPath = path.join(process.cwd(), 'Acme_Enterprises-401k-Draft-OnboardingPackage.pdf')
  fs.writeFileSync(pkgPath, pkgBuffer)
  console.log(`Generated: ${pkgPath} (${pkgBuffer.length} bytes)`)

  console.log('\nSuccess! Draft PDFs created in project root.')
}

main().catch(err => {
  console.error('Error generating draft PDFs:', err)
  process.exit(1)
})
